### ISSUE TITLE
Invalid Status Code 'NOT FOUND' at Microsoft.Azure.Management.Billing.Models.ErrorResponseException

### ISSUE THREAD

**Issue by jayendranarumugam** [Azure-Samples/billing-dotnet-core-invoice-download#1]
Hi all,

After changing the app.json to pointing my Azure account. I'm getting the below error.This is due to Invoice is not present for my Azure account.So we have to handle the exception and give a meaningful error instead of full stack trace

**Full Stacktrace:**
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation returned an invalid status code 'NotFound') ---> Microsoft.Azure.Management.Billing.Models.ErrorResponseException: Operation returned an invalid status code 'NotFound'
   at Microsoft.Azure.Management.Billing.InvoicesOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Billing.InvoicesOperationsExtensions.<ListAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Billing.InvoicesOperationsExtensions.List(IInvoicesOperations operations, String expand, String filter, String skiptoken, Nullable`1 top)
   at billing_dotnet_invoice_api.Program.<Run>d__6.MoveNext() in D:\New folder\billing-dotnet-core-invoice-download\Program.cs:line 35
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
```

**Comment by jayendranarumugam** [comment]
Seems this repo is lost or not maintained properly. So closing the Issue
