### ISSUE TITLE
 invalid status code 'BadRequest'

### ISSUE THREAD

**Issue by sivakrkumar** [Azure-Samples/billing-dotnet-core-invoice-download#2]
System.AggregateException: 'One or more errors occurred. (Operation returned an invalid status code 'BadRequest')'.

**Comment by sagarkul** [comment]
```
Microsoft.Azure.Management.Billing.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Billing.InvoicesOperations.ListWithHttpMessagesAsync(String expand, String filter, String skiptoken, Nullable`1 top, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Billing.InvoicesOperationsExtensions.ListAsync(IInvoicesOperations operations, String expand, String filter, String skiptoken, Nullable`1 top, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Billing.InvoicesOperationsExtensions.List(IInvoicesOperations operations, String expand, String filter, String skiptoken, Nullable`1 top)
   at billing_dotnet_invoice_api.Program.Run() in C:\GitHub\billing-dotnet-core-invoice-download\Program.cs:line 37
```
