### ISSUE TITLE
Forbidden 

### ISSUE THREAD

**Issue by goochi1** [Azure-Samples/billing-dotnet-core-invoice-download#3]
Calling invoice service for all available invoices...

Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation returned an invalid status code 'Forbidden') ---> Microsoft.Azure.Management.Billing.Models.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Azure.Management.Billing.InvoicesOperations.ListWithHttpMessagesAsync(String expand, String filter, String skiptoken, Nullable`1 top, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Billing.InvoicesOperationsExtensions.ListAsync(IInvoicesOperations operations, String expand, String filter, String skiptoken, Nullable`1 top, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Billing.InvoicesOperationsExtensions.List(IInvoicesOperations operations, String expand, String filter, String skiptoken, Nullable`1 top)
   at billing_dotnet_invoice_api.Program.Run() in /Users/sgooch/Documents/Stash/azure/billing-dotnet-core-invoice-download/Program.cs:line 35
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at billing_dotnet_invoice_api.Program.Main(String[] args) in /Users/sgooch/Documents/Stash/azure/billing-dotnet-core-invoice-download/Program.cs:line 26

**Comment by lorenzosoncini** [comment]
I have the same problem. Where we can assign permission to access Azure Invoice Api ?
I have tried with "Microsoft Invoicing/app_access" but the error is the same.

**Comment by Jacintopc** [comment]
I had the same problem. Solved by adding the role of "Billing Reader" to the service principal created for the application (https://docs.microsoft.com/es-es/azure/active-directory/develop/howto-create-service-principal-portal). You have to use the service principal ID. See attached image: 
<img width="424" alt="Captura de pantalla 2019-07-17 a las 12 34 21" src="https://user-images.githubusercontent.com/10612048/61368975-59174e00-a88f-11e9-8849-c43ba017fc8d.png">
